### ISSUE TITLE
Checklist Dashboard screen

### ISSUE THREAD

**Issue by christoph-codes** [christoph-codes/kikstarterz#76]
A screen that helps users complete their profile in its entirety. Gamify it with a progress bar.
- [x] Fill out the profile
- [x] add headshot
- [x] add 3 action photos
- [x] Share your profile
- [x] Invite one teammate
